---
ip_management: "{{ vlan_management.ip }}.100"
qnap_qsw_m2116p_2t2s_admin_password: "{{ vault_password }}"
qnap_qsw_m2116p_2t2s_ports:
  1:
    description: morbo
    poe: true
    tagged:
      - management
      - trusted
      - iot
      - guest
  3:
    description: hypnotoad
    untagged: networking
  4:
    description: mom
    untagged: management
  6:
    description: nibbler-eth2
    tagged:
      - management
      - servers
      - automation
      - networking
  8:
    description: nibbler-eth1
    untagged: lan
    tagged:
      - management
      - servers
      - security
      - automation
      - networking
      - trusted
      - iot
      - guest
  17:
    description: sal
    untagged: lan
    tagged:
      - management
      - trusted
      - iot
      - guest
  18:
    description: hermes
    tagged:
      - management
      - servers
