---
admin: zoidberg
ansible_user: "{{ admin }}"
domain: bradleydavis.tech
domain_lan: lan.{{ domain }}
timezone: America/Los_Angeles
host_connection: ssh
ip_top: 10
vlan_lan:
  name: lan
  id: 1
  ip: "{{ ip_top }}.0.1"
vlan_management:
  name: management
  id: 88
  ip: "{{ ip_top }}.0.88"
vlan_servers:
  name: servers
  id: 101
  ip: "{{ ip_top }}.10.1"
vlan_security:
  name: security
  id: 201
  ip: "{{ ip_top }}.20.1"
vlan_automation:
  name: automation
  id: 301
  ip: "{{ ip_top }}.30.1"
vlan_networking:
  name: networking
  id: 401
  ip: "{{ ip_top }}.40.1"
vlan_trusted:
  name: trusted
  id: 701
  ip: "{{ ip_top }}.70.1"
vlan_iot:
  name: iot
  id: 801
  ip: "{{ ip_top }}.80.1"
vlan_guest:
  name: guest
  id: 901
  ip: "{{ ip_top }}.90.1"
#   2 -  19: Commonly visited services are low numbered
#  20 -  99: Other services
# 100 - 199: Bare metal hosts end in a zero, virtualized are 1-9
# 200 - 254: DHCP
ip_grafana: "{{ vlan_management.ip }}.2"
ip_uptime: "{{ vlan_management.ip }}.3"
ip_prometheus: "{{ vlan_management.ip }}.20"
ip_alertmanager: "{{ vlan_management.ip }}.21"
# ip_blackbox_exporter: "{{ vlan_management.ip }}.22"
ip_dns_exporter_0: "{{ vlan_management.ip }}.23"
ip_dns_exporter_1: "{{ vlan_management.ip }}.24"
ip_speedtest_exporter: "{{ vlan_management.ip }}.25"
ip_ntp_exporter: "{{ vlan_management.ip }}.26"
ip_nginx_exporter: "{{ vlan_management.ip }}.27"
ip_pve_exporter: "{{ vlan_management.ip }}.28"
# ip_plex: "{{ vlan_servers.ip }}.2"
# ip_wiki: "{{ vlan_servers.ip }}.3"
ip_nummus: "{{ vlan_servers.ip }}.4"
# ip_wiki_db: "{{ vlan_servers.ip }}.20"

ip_home_assistant: "{{ vlan_automation.ip }}.2"
ip_dns_0: "{{ vlan_networking.ip }}.2"
ip_dns_1: "{{ vlan_networking.ip }}.3"
ip_ntp: "{{ vlan_networking.ip }}.4"
ip_reverse_proxy: "{{ vlan_networking.ip }}.5"
# ip_reverse_proxy_public: "{{ vlan_networking.ip }}.6"
ip_ddns: "{{ vlan_networking.ip }}.20"
# ip_greenhouse: "{{ vlan_iot.ip }}.20"
ip_beehive: "{{ vlan_iot.ip }}.21"
# Vault items
sysadmin_email: "{{ vault_sysadmin_email }}"
pihole_admin_password: "{{ vault_pihole_admin_password }}"
uptime_admin_password: "{{ vault_uptime_admin_password }}"
uptime_discord: "{{ vault_uptime_discord }}"
cloudflare_certbot_api_token: "{{ vault_cloudflare_certbot_api_token }}"
cloudflare_ddns_api_token: "{{ vault_cloudflare_ddns_api_token }}"
certbot_discord: "{{ vault_certbot_discord }}"
alertmanager_discord: "{{ vault_alertmanager_discord }}"
grafana_admin_password: "{{ vault_grafana_admin_password }}"
pve_token: "{{ vault_pve_token }}"
wap_key: "{{ vault_wap_key }}"
wap_iot_key: "{{ vault_wap_iot_key }}"
wap_guest_key: "{{ vault_wap_guest_key }}"
