---
- name: Read WAX620 time settings
  ansible.builtin.uri:
    url: "https://{{ netgear_wax620_host }}/socketCommunication"
    method: POST
    body_format: json
    body:
      system:
        timeSettings:
          timeZone: ""
          ntpClientStatus: ""
          customNtpServer: ""
          ntpAddr: ""
          ntpAddrType: ""
        monitor:
          currentTime: ""
    headers: "{{ netgear_wax620_session_headers }}"
    return_content: true
    status_code: 200
    timeout: "{{ netgear_wax620_timeout_s }}"
    validate_certs: "{{ netgear_wax620_validate_certs }}"
  register: netgear_wax620_time_settings_response
  changed_when: false
  failed_when: >-
    (netgear_wax620_time_settings_response.content | from_json).status | default(-1) | int != 0
- name: Extract current WAX620 time settings
  ansible.builtin.set_fact:
    netgear_wax620_time_settings_current:
      timeZone: >-
        {{ (netgear_wax620_time_settings_response.content | from_json).system.timeSettings.timeZone }}
      ntpClientStatus: >-
        {{ (netgear_wax620_time_settings_response.content | from_json).system.timeSettings.ntpClientStatus }}
      customNtpServer: >-
        {{ (netgear_wax620_time_settings_response.content | from_json).system.timeSettings.customNtpServer }}
      ntpAddr: >-
        {{ (netgear_wax620_time_settings_response.content | from_json).system.timeSettings.ntpAddr }}
      ntpAddrType: >-
        {{ (netgear_wax620_time_settings_response.content | from_json).system.timeSettings.ntpAddrType }}
- name: Set desired WAX620 time settings
  ansible.builtin.set_fact:
    netgear_wax620_time_settings_desired:
      timeZone: "{{ netgear_wax620_time_zone_ids[netgear_wax620_timezone] }}"
      ntpClientStatus: "1"
      customNtpServer: "1"
      ntpAddr: "{{ netgear_wax620_ntp_server }}"
      ntpAddrType: "0"
- name: Update WAX620 time settings
  ansible.builtin.uri:
    url: "https://{{ netgear_wax620_host }}/socketCommunication"
    method: POST
    body_format: json
    body:
      system:
        timeSettings: "{{ netgear_wax620_time_settings_desired }}"
    headers: "{{ netgear_wax620_session_headers }}"
    return_content: true
    status_code: 200
    timeout: "{{ netgear_wax620_timeout_s }}"
    validate_certs: "{{ netgear_wax620_validate_certs }}"
  register: netgear_wax620_time_settings_update
  when: >-
    netgear_wax620_time_settings_current != netgear_wax620_time_settings_desired
  changed_when: true
  failed_when: >-
    (netgear_wax620_time_settings_update.content | from_json).status | default(-1) | int != 0
