---
eth_management_mac: "6A:20:0E:9A:CD:19"
eth_services_mac: "42:94:98:9A:0C:5C"

ip_management: "{{ vlan_management.ip }}.111"
ip_cadvisor: "{{ vlan_management.ip }}.119"

is_dns_primary: true
is_baremetal: false

vlans:
  - name: management
  - name: servers
    ip: "{{ ip_nummus }}"
  - name: networking
vlans_extras:
  eth-mgmt:
    match:
      macaddress: "{{ eth_management_mac }}"
      name: e*
    set-name: eth-mgmt
    addresses:
      - "{{ ip_management }}/24"
    routes:
      - to: default
        via: "{{ vlan_management.ip }}.1"
    nameservers:
      search:
        - "{{ domain_lan }}"
      addresses:
        - "{{ ip_dns_0 }}"
        - "{{ ip_dns_1 }}"
vlan_hw_offload: false
