---
eth_services_mac: "{{ bridge_mac_eth_0 }}"

ip_management: "{{ vlan_management.ip }}.111"
ip_cadvisor: "{{ vlan_management.ip }}.119"

is_dns_primary: true
is_baremetal: false

vlans:
  - name: management
    ip: "{{ ip_management }}"
    default_route: true
  - name: servers
    ip: "{{ ip_nummus }}"
  - name: networking
vlan_hw_offload: false
