---
- name: |-
    {{
      qnap_qsw_m2116p_2t2s_vlan_change_requested.action
      + ' QSW-M2116P-2T2S VLAN '
      + qnap_qsw_m2116p_2t2s_vlan_change_requested.vlan_id
    }}
  ansible.builtin.uri:
    url: |-
      {{
        'http://'
        + qnap_qsw_m2116p_2t2s_active_host
        + '/api/v3/'
        + (qnap_qsw_m2116p_2t2s_vlan_change_requested.path | default('vlan'))
      }}
    method: "{{ qnap_qsw_m2116p_2t2s_vlan_change_requested.method }}"
    body_format: raw
    body: "{{ qnap_qsw_m2116p_2t2s_vlan_change_requested.body | to_json }}"
    headers: "{{ qnap_qsw_m2116p_2t2s_session_headers }}"
    return_content: true
    status_code: 200
    timeout: "{{ qnap_qsw_m2116p_2t2s_request_timeout_s }}"
  register: qnap_qsw_m2116p_2t2s_vlan_change_response
  no_log: true
  changed_when: |-
    qnap_qsw_m2116p_2t2s_vlan_change_response.status
    | default(-1)
    | int == 200 and qnap_qsw_m2116p_2t2s_vlan_change_response.json.error_code
    | default(-1)
    | int == 200
  failed_when: false
- name: |-
    {{
      'Collect failed QSW-M2116P-2T2S VLAN '
      + qnap_qsw_m2116p_2t2s_vlan_change_requested.vlan_id
      + ' '
      + (qnap_qsw_m2116p_2t2s_vlan_change_requested.action | lower)
    }}
  ansible.builtin.set_fact:
    qnap_qsw_m2116p_2t2s_vlan_change_failures: |-
      {{
        qnap_qsw_m2116p_2t2s_vlan_change_failures
        + [
          {
            'action': qnap_qsw_m2116p_2t2s_vlan_change_requested.action,
            'vlan_id': qnap_qsw_m2116p_2t2s_vlan_change_requested.vlan_id,
            'http_status': qnap_qsw_m2116p_2t2s_vlan_change_response.status | default(-1),
            'error_code': qnap_qsw_m2116p_2t2s_vlan_change_result.error_code | default(-1),
            'error_message': qnap_qsw_m2116p_2t2s_vlan_change_result.error_message
            | default('No QSS error message'),
          }
        ]
      }}
  vars:
    qnap_qsw_m2116p_2t2s_vlan_change_result: |-
      {{ qnap_qsw_m2116p_2t2s_vlan_change_response.json | default({}) }}
  no_log: true
  when: |-
    qnap_qsw_m2116p_2t2s_vlan_change_response.status
    | default(-1)
    | int != 200 or qnap_qsw_m2116p_2t2s_vlan_change_result.error_code
    | default(-1)
    | int != 200
