---
# vm0.nibbler needs hostnames to bare metal in order to SSH to them.
- name: Generate /etc/hosts file on vm0.nibbler
  hosts: vm0.nibbler
  roles:
    - role: etc_hosts
      etc_hosts_list: "{{ groups['etc_hosts'] }}"
- name: Setup nameservers
  hosts: nameservers
  roles:
    - role: pihole
      become: true
      pihole_hostname: "{{ is_dns_primary | ternary('pihole0', 'pihole1')}}"
      pihole_domain: "{{ domain_lan }}"
      pihole_password: "{{ pihole_admin_password }}"
      pihole_network: "{{ 'vlan-' + vlan_networking.name }}"
      pihole_ip: "{{ is_dns_primary | ternary(ip_dns_0, ip_dns_1) }}"
      pihole_dhcp_subnet: "10.0.0.0/8"
      pihole_dhcp_server: "{{ vlan_networking.ip }}.1"
      pihole_wildcard:
        - domain: "{{ domain_lan }}"
          ip: "{{ ip_reverse_proxy }}"
      pihole_extra_hosts:
        - host: direct.dns0
          ip: "{{ ip_dns_0 }}"
        - host: direct.dns1
          ip: "{{ ip_dns_1 }}"
        - host: ntp
          ip: "{{ ip_ntp }}"
        - host: pfsense
          ip: "{{ hostvars['pfsense.nibbler'].ip_management }}"
- name: Install dynamic DNS
  hosts: vm0.nibbler
  tasks:
    - name: Install cloudflare-ddns
      become: true
      community.docker.docker_container:
        name: ddns
        image: oznu/cloudflare-ddns:latest
        networks:
          - name: "{{ 'vlan-' + vlan_networking.name }}"
            ipv4_address: "{{ ip_ddns }}"
        restart_policy: unless-stopped
        state: started
        env:
          ZONE: "{{ domain }}"
          API_KEY: "{{ cloudflare_ddns_api_token }}"
          SUBDOMAIN: site01
          PROXIED: "false"
